/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as QualifyRouteImport } from './routes/qualify'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWeightLossRouteImport } from './routes/services.weight-loss'
import { Route as ServicesProgesteroneEstrogenRouteImport } from './routes/services.progesterone-estrogen'
import { Route as ServicesPeptideTherapyRouteImport } from './routes/services.peptide-therapy'
import { Route as ServicesIvTherapyRouteImport } from './routes/services.iv-therapy'
import { Route as ServicesHormoneTherapyWomenRouteImport } from './routes/services.hormone-therapy-women'
import { Route as ServicesHormoneTherapyMenRouteImport } from './routes/services.hormone-therapy-men'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const QualifyRoute = QualifyRouteImport.update({
  id: '/qualify',
  path: '/qualify',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWeightLossRoute = ServicesWeightLossRouteImport.update({
  id: '/services/weight-loss',
  path: '/services/weight-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProgesteroneEstrogenRoute =
  ServicesProgesteroneEstrogenRouteImport.update({
    id: '/services/progesterone-estrogen',
    path: '/services/progesterone-estrogen',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPeptideTherapyRoute = ServicesPeptideTherapyRouteImport.update({
  id: '/services/peptide-therapy',
  path: '/services/peptide-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIvTherapyRoute = ServicesIvTherapyRouteImport.update({
  id: '/services/iv-therapy',
  path: '/services/iv-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHormoneTherapyWomenRoute =
  ServicesHormoneTherapyWomenRouteImport.update({
    id: '/services/hormone-therapy-women',
    path: '/services/hormone-therapy-women',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHormoneTherapyMenRoute =
  ServicesHormoneTherapyMenRouteImport.update({
    id: '/services/hormone-therapy-men',
    path: '/services/hormone-therapy-men',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/qualify': typeof QualifyRoute
  '/terms': typeof TermsRoute
  '/services/hormone-therapy-men': typeof ServicesHormoneTherapyMenRoute
  '/services/hormone-therapy-women': typeof ServicesHormoneTherapyWomenRoute
  '/services/iv-therapy': typeof ServicesIvTherapyRoute
  '/services/peptide-therapy': typeof ServicesPeptideTherapyRoute
  '/services/progesterone-estrogen': typeof ServicesProgesteroneEstrogenRoute
  '/services/weight-loss': typeof ServicesWeightLossRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/qualify': typeof QualifyRoute
  '/terms': typeof TermsRoute
  '/services/hormone-therapy-men': typeof ServicesHormoneTherapyMenRoute
  '/services/hormone-therapy-women': typeof ServicesHormoneTherapyWomenRoute
  '/services/iv-therapy': typeof ServicesIvTherapyRoute
  '/services/peptide-therapy': typeof ServicesPeptideTherapyRoute
  '/services/progesterone-estrogen': typeof ServicesProgesteroneEstrogenRoute
  '/services/weight-loss': typeof ServicesWeightLossRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/qualify': typeof QualifyRoute
  '/terms': typeof TermsRoute
  '/services/hormone-therapy-men': typeof ServicesHormoneTherapyMenRoute
  '/services/hormone-therapy-women': typeof ServicesHormoneTherapyWomenRoute
  '/services/iv-therapy': typeof ServicesIvTherapyRoute
  '/services/peptide-therapy': typeof ServicesPeptideTherapyRoute
  '/services/progesterone-estrogen': typeof ServicesProgesteroneEstrogenRoute
  '/services/weight-loss': typeof ServicesWeightLossRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/privacy'
    | '/qualify'
    | '/terms'
    | '/services/hormone-therapy-men'
    | '/services/hormone-therapy-women'
    | '/services/iv-therapy'
    | '/services/peptide-therapy'
    | '/services/progesterone-estrogen'
    | '/services/weight-loss'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/privacy'
    | '/qualify'
    | '/terms'
    | '/services/hormone-therapy-men'
    | '/services/hormone-therapy-women'
    | '/services/iv-therapy'
    | '/services/peptide-therapy'
    | '/services/progesterone-estrogen'
    | '/services/weight-loss'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/privacy'
    | '/qualify'
    | '/terms'
    | '/services/hormone-therapy-men'
    | '/services/hormone-therapy-women'
    | '/services/iv-therapy'
    | '/services/peptide-therapy'
    | '/services/progesterone-estrogen'
    | '/services/weight-loss'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  QualifyRoute: typeof QualifyRoute
  TermsRoute: typeof TermsRoute
  ServicesHormoneTherapyMenRoute: typeof ServicesHormoneTherapyMenRoute
  ServicesHormoneTherapyWomenRoute: typeof ServicesHormoneTherapyWomenRoute
  ServicesIvTherapyRoute: typeof ServicesIvTherapyRoute
  ServicesPeptideTherapyRoute: typeof ServicesPeptideTherapyRoute
  ServicesProgesteroneEstrogenRoute: typeof ServicesProgesteroneEstrogenRoute
  ServicesWeightLossRoute: typeof ServicesWeightLossRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualify': {
      id: '/qualify'
      path: '/qualify'
      fullPath: '/qualify'
      preLoaderRoute: typeof QualifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/weight-loss': {
      id: '/services/weight-loss'
      path: '/services/weight-loss'
      fullPath: '/services/weight-loss'
      preLoaderRoute: typeof ServicesWeightLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/progesterone-estrogen': {
      id: '/services/progesterone-estrogen'
      path: '/services/progesterone-estrogen'
      fullPath: '/services/progesterone-estrogen'
      preLoaderRoute: typeof ServicesProgesteroneEstrogenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/peptide-therapy': {
      id: '/services/peptide-therapy'
      path: '/services/peptide-therapy'
      fullPath: '/services/peptide-therapy'
      preLoaderRoute: typeof ServicesPeptideTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/iv-therapy': {
      id: '/services/iv-therapy'
      path: '/services/iv-therapy'
      fullPath: '/services/iv-therapy'
      preLoaderRoute: typeof ServicesIvTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hormone-therapy-women': {
      id: '/services/hormone-therapy-women'
      path: '/services/hormone-therapy-women'
      fullPath: '/services/hormone-therapy-women'
      preLoaderRoute: typeof ServicesHormoneTherapyWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hormone-therapy-men': {
      id: '/services/hormone-therapy-men'
      path: '/services/hormone-therapy-men'
      fullPath: '/services/hormone-therapy-men'
      preLoaderRoute: typeof ServicesHormoneTherapyMenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  QualifyRoute: QualifyRoute,
  TermsRoute: TermsRoute,
  ServicesHormoneTherapyMenRoute: ServicesHormoneTherapyMenRoute,
  ServicesHormoneTherapyWomenRoute: ServicesHormoneTherapyWomenRoute,
  ServicesIvTherapyRoute: ServicesIvTherapyRoute,
  ServicesPeptideTherapyRoute: ServicesPeptideTherapyRoute,
  ServicesProgesteroneEstrogenRoute: ServicesProgesteroneEstrogenRoute,
  ServicesWeightLossRoute: ServicesWeightLossRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
